name: BlurPaint
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip:
    - pytorch-lightning==1.9.4
    - albumentations==1.3.1
    - omegaconf==2.3.0
    - lpips==0.1.4
    - pytorch-fid==0.3.0
    - pillow==9.4.0
    - six==1.16.0
    - timm==0.9.16
    - causal_conv1d==1.1.1
    - mamba-ssm==1.1.1